version: '3'
services:
  app:
    image: node:12.18.0
    volumes:
      - .:/src/vue-svg-jest-sample
      - node_modules:/src/vue-svg-jest-sample/node_modules:delegated
    command: tail -f /dev/null
volumes: 
  node_modules: